### ISSUE TITLE
Factual error in Why

### ISSUE THREAD

**Issue by mattiasaxell** [civictechsweden/oppna-atervinningsdata#1]
> And since they aren't public sector, no one has actually asked FTI AB if they could publish the list.
- https://github.com/civictechsweden/oppna-atervinningsdata/blob/master/README.md

This is not correct. Seems we have talked to different people, unknowingly of each others efforts - again. :) I'd love some more context to this project. Who, what, when, how et.c. about efforts with FTI AB.

**Comment by PierreMesure** [comment]
Hi Mattias, I asked several people who've been in open data in Sweden for a while, among which Björn. He couldn't remember that FTI had been asked in any of the projects he'd been involved. I should have asked you as well. Can you tell me what you know?

**Comment by mattiasaxell** [comment]
@PierreMesure OK. FTI has been asked in the VGR collaboration or start of Nationell Dataverkstad but maybe that was before involvement of @bjornhagstrom. :) Good that I got noticed by Github re the start of this repo. The best I know is something I think will be developed here: https://gitlab.com/sarskilt-vardefulla-datamangder/atervinningsstationer/-/issues/1

**Comment by bjornhagstrom** [comment]
@mattiasaxell Yes I think that must have been before I got involved in Dataverkstaden.
